In [13]:
### Assignment 1: Array Creation and Manipulation
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
# Replace all the elements in the third column with 1.
import random
import numpy as np
data=np.random.randint(1,21,size=(5,5))
# print(data)
# data=data.reshape(4,5)
print(data)


data[0:5,2]=1

print('----------------------------------------')
print(data)

[[15  2  6  3  9]
 [12  9 12  1 14]
 [ 8 10  1 14  1]
 [ 4  1 12 15 19]
 [ 7  6 13 18 15]]
----------------------------------------
[[15  2  1  3  9]
 [12  9  1  1 14]
 [ 8 10  1 14  1]
 [ 4  1  1 15 19]
 [ 7  6  1 18 15]]


In [4]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
# Replace the diagonal elements with 0.
arr=np.arange(1,17)
arr=arr.reshape(4,4)
arr

np.fill_diagonal(arr,0)
arr




array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [12]:

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr=np.arange(1,37).reshape(6,6)
print(arr)

sub_arr=np.array(arr[2:5,1:4])
sub_arr



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [44]:

# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr=np.random.randint(21,size=(5,5))
print(arr)
print('-------------------')
top=arr[0,:]
print(top)
print('-------------------')
bottom=arr[4,0:]
print(bottom)
print('-------------------')
left=arr[1:4,0]
print(left)

print('-------------------')
right_side=arr[1:4,4]
print(right_side)
border_elements = np.concatenate([top, right_side, bottom, left])
border_elements


[[10  2 14 20  9]
 [ 1 10 10 12 19]
 [ 9 17 13  0 18]
 [ 3  2 18  1  2]
 [17  3  8  6  5]]
-------------------
[10  2 14 20  9]
-------------------
[17  3  8  6  5]
-------------------
[1 9 3]
-------------------
[19 18  2]


array([10,  2, 14, 20,  9, 19, 18,  2, 17,  3,  8,  6,  5,  1,  9,  3],
      dtype=int32)

In [50]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.

arr1=np.random.randint(1,21,size=(3,4))
print("ARRAy 1:\n ",arr1)

arr2=np.random.randint(1,21,size=(3,4))
print("ARRAy 2:\n ",arr2)
print('-------------------')
print(arr1+arr2)
print('-------------------')
print(arr1-arr2)
print('-------------------')
print(arr1*arr2)
print('-------------------')
print(arr1/arr2)



ARRAy 1:
  [[12  2  1  1]
 [ 7  7 19 18]
 [ 4 12 13  4]]
ARRAy 2:
  [[18  6  2 10]
 [11 17 13 18]
 [ 2 19  6 15]]
-------------------
[[30  8  3 11]
 [18 24 32 36]
 [ 6 31 19 19]]
-------------------
[[ -6  -4  -1  -9]
 [ -4 -10   6   0]
 [  2  -7   7 -11]]
-------------------
[[216  12   2  10]
 [ 77 119 247 324]
 [  8 228  78  60]]
-------------------
[[0.66666667 0.33333333 0.5        0.1       ]
 [0.63636364 0.41176471 1.46153846 1.        ]
 [2.         0.63157895 2.16666667 0.26666667]]


In [ ]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr=np.random.randint(1,17,size=(4,4))
print(arr)



row_wise=np.sum(arr,axis=1)
print(row_wise)
col_wise=np.sum(arr,axis=0)
print(col_wise)



[[12 12 13  9]
 [ 9  3  8  1]
 [ 5  9  6 10]
 [ 7  1 10 13]]
[33 25 37 33]
[46 21 30 31]


In [63]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr=np.random.randint(1,26,size=(5,5))
mean=np.mean(arr)
median=np.median(arr)
sd=np.std(arr)
variance = np.var(arr)

print(mean)
print(median)
print(sd)
print(variance)

13.0
14.0
8.337865434270332
69.52


In [64]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr=np.random.randint(1,26,size=(5,5))
mean=np.mean(arr)
sd=np.std(arr)

print(mean)
print(sd)
normalized_arr=(arr-mean)/sd

print(normalized_arr)

12.12
7.262616608358175
[[-0.01652297  1.7734655   1.36039124 -0.15421439 -1.39343718]
 [-1.11805434  0.39655129 -0.98036292  0.25885987 -0.70498007]
 [ 0.67193413 -0.56728865 -0.8426715  -0.8426715   1.63577408]
 [-0.15421439  1.63577408 -0.29190581 -1.11805434  1.49808266]
 [-0.42959723  1.36039124 -0.01652297 -0.98036292 -0.98036292]]
