In [21]:
import numpy as np
arr1=np.array(['rohini','arty','rakhi',3,5,6])
print("Single dimnesional array \n ",arr1)
print(arr1.shape)
print(arr1.size)
print(arr1)
print(type(arr1))


Single dimnesional array 
  ['rohini' 'arty' 'rakhi' '3' '5' '6']
(6,)
6
['rohini' 'arty' 'rakhi' '3' '5' '6']
<class 'numpy.ndarray'>


In [27]:
arr1 = arr1.reshape(2,3) 

print("Multidimnesional array \n ",arr1)
print(arr1.shape)
print(type(arr1))


Multidimnesional array 
  [['rohini' 'arty' 'rakhi']
 ['3' '5' '6']]
(2, 3)
<class 'numpy.ndarray'>


In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Multidimnesional array \n ",arr2)
print(arr1.shape)

Multidimnesional array 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
arr2=np.arange(0,12,2)
print(arr2)
arr2=arr2.reshape(3,2)
print("Multidimnesional array \n ",arr2)

[ 0  2  4  6  8 10]
Multidimnesional array 
  [[ 0  2]
 [ 4  6]
 [ 8 10]]


In [34]:
arr_1=np.arange(1,11,2).reshape(5,1)
print(arr_1)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [49]:
arr1=np.array([1,4,9,16,25,36])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(arr1)

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
[ 1  4  9 16 25 36]


In [62]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]]
             )

print(arr)
print('-----------------------------------')
print(arr[0])
print('-----------------------------------')
print(arr[0][2])
print('-----------------------------------')
print(arr[0:3,1:])
print('-----------------------------------')
print(arr[1:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------------
[1 2 3]
-----------------------------------
3
-----------------------------------
[[2 3]
 [5 6]
 [8 9]]
-----------------------------------
[[5 6]
 [8 9]]
