In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
#create array using Numpy
##CReating 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
print(arr2)
print(arr2.shape)


[1 2 3 4 5]
(5,)


In [ ]:
np.arange(0,10,2).reshape(5,1) 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
arr=np.array([[1,2,3], [4,5,6],[7,8,9]])
print('Array: \n',arr)
print('Shape: ',arr.shape)
print('Dimension ',arr.ndim)
print('Data type ' ,arr.dtype)
print('Size ',arr.size)
print('Item size ',arr.itemsize)


Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Dimension  2
Data type  int64
Size  9
Item size  8


In [15]:
#Vectorized opr
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [ ]:
#Universal function
arr1=np.array([1,4,7,16,25])
print(np.sqrt(arr1))
print(np.square(arr1))
print(np.exp(arr1))

[1.         2.         2.64575131 4.         5.        ]
[  1  16  49 256 625]
[2.71828183e+00 5.45981500e+01 1.09663316e+03 8.88611052e+06
 7.20048993e+10]


In [23]:
#Slicing and Indexing
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

print(arr1[0][0])
print(arr1[1:,2:])
print(arr1[0:2,:2])



#Modify element
arr1[0][2]=10

print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[1 2]
 [5 6]]
[[ 1  2 10  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Calculate mean,median,std,variance and normalized data

data=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.std(data)
print(std_dev)

variance=np.var(data)
print(variance)

normalized_data= (data-mean)/std_dev
print(normalized_data)


5.5
5.5
2.8722813232690143
8.25
[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
